schema.yaml:
openapi: 3.0.0
info:
  version: 1.0.1
  title: Get Session and Token API
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_checkoutsession_rw: Create and return session and token
        clientCredentials:
          tokenUrl: https://my-shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_checkoutsession_rw: Create and return session and token
paths:
  /checkoutsession:
    post:
      summary: Create the Auth Token and Session ID
      operationId: createCheckoutSession
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: locale
          required: false
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: Returns created Auth Token and Session ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  length:
                    type: number
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        token:
                          type: string
                        sessionId:
                          type: string
        "404":
          description: Returns general errors
          content:
            application/json:
              examples:
                not_found:
                  value:
                    {
                      "type": "page not found",
                    }
security:
  - AmOAuth2: ["c_checkoutsession_rw"]
